triggers:
  - harbor:
      version: 2
      entryPoint: deploy
      conditions:
        type: pushImage
        event_data:
          resources:
            - tag: latest
          repository:
            name: starburst-cloud

configuration:
  runtime: concord-v2

flows:
  default:
    - log: "Hello!"
